"""add 

Revision ID: 2935dcc34d98
Revises: a8cedc5714f7
Create Date: 2025-08-05 08:56:34.099028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2935dcc34d98'
down_revision = 'a8cedc5714f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('user_type_visibility', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('user_type_visibility')
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
