"""Update all models with latest changes

Revision ID: a2515649af0d
Revises: eb0ffa0f1382
Create Date: 2025-07-21 17:43:46.272256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2515649af0d'
down_revision = 'eb0ffa0f1382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_settings_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('external_product_id', sa.String(length=100), nullable=False),
    sa.Column('reseller_ref_number', sa.String(length=100), nullable=False),
    sa.Column('transaction_status', sa.String(length=20), nullable=True),
    sa.Column('purchase_response', sa.Text(), nullable=True),
    sa.Column('product_codes', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_settings_id'], ['api_settings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reseller_ref_number')
    )
    op.create_table('api_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_settings_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('external_product_id', sa.String(length=100), nullable=False),
    sa.Column('provider_product_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('provider_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('provider_currency', sa.String(length=3), nullable=True),
    sa.Column('stock_status', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('sync_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_settings_id'], ['api_settings.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_key', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reseller_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('api_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_sync', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_product_category', 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_product_subcategory', 'subcategory', ['subcategory_id'], ['id'])

    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.alter_column('regular_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('kyc_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('google_id')
        batch_op.drop_column('username')

    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('kyc_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('regular_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_subcategory', type_='foreignkey')
        batch_op.drop_constraint('fk_product_category', type_='foreignkey')

    with op.batch_alter_table('api_settings', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('last_sync')
        batch_op.drop_column('api_type')
        batch_op.drop_column('reseller_username')
        batch_op.drop_column('secret_key')

    op.drop_table('api_product')
    op.drop_table('api_transaction')
    # ### end Alembic commands ###
