"""add_visibility_column2

Revision ID: cc73a9b5ab4a
Revises: 4c41d18aafab
Create Date: 2025-07-19 22:46:27.228587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc73a9b5ab4a'
down_revision = '4c41d18aafab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'subcategory', ['subcategory_id'], ['id'])
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('kyc_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('note')
        batch_op.drop_column('kyc_price')
        batch_op.drop_column('regular_price')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
