"""Add advanced product controls

Revision ID: d4829d6d0655
Revises: 
Create Date: 2025-07-19 22:38:58.451221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4829d6d0655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_category')
    op.drop_table('short_category')
    op.drop_table('gift_card')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcategory', ['subcategory_id'], ['id'])

    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('kyc_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('note')
        batch_op.drop_column('kyc_price')
        batch_op.drop_column('regular_price')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visibility')

    op.create_table('gift_card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=300), nullable=False),
    sa.Column('link_url', sa.VARCHAR(length=300), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('link_url', sa.VARCHAR(length=300), nullable=False),
    sa.Column('icon_class', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quick_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('icon_class', sa.VARCHAR(length=100), nullable=False),
    sa.Column('link_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
