"""add wallet systm

Revision ID: eb0ffa0f1382
Revises: 
Create Date: 2025-07-20 08:37:54.452760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0ffa0f1382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_product_subcategory', 'subcategory', ['subcategory_id'], ['id'])
        batch_op.create_foreign_key('fk_product_category', 'category', ['category_id'], ['id'])

    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.alter_column('regular_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('kyc_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_custom_price', schema=None) as batch_op:
        batch_op.alter_column('custom_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('kyc_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('regular_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_subcategory', type_='foreignkey')
        batch_op.drop_constraint('fk_product_category', type_='foreignkey')

    # ### end Alembic commands ###
